# Generated by Django 3.0 on 2021-09-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210915_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Garden'),
        ),
    ]
