# Generated by Django 3.0 on 2021-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210915_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='image',
        ),
        migrations.AddField(
            model_name='seed',
            name='in_garden',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
