# Generated by Django 3.0 on 2021-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210915_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
