# Generated by Django 3.0 on 2021-09-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210916_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='in_garden',
            new_name='planted',
        ),
    ]
