# Generated by Django 3.0 on 2021-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210916_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='garden',
        ),
        migrations.AlterField(
            model_name='seed',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
