# Generated by Django 3.0 on 2021-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210917_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='light',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seed',
            name='season',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seed',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
